### ISSUE TITLE
[MainThread  ] [ERROR]  Uncaught exception

### ISSUE THREAD

**Issue by dimat789** [Nalorokk/ultracam#2]
После команды  python main.py возникает ошибка

dimat789@ubuntu-vm:~/ultracam$ python main.py
2022-03-02 14:50:42,237 [MainThread  ] [DEBUG]  Found GEOS DLL: <CDLL '/home/dimat789/.local/lib/python3.6/site-packages/Shapely.libs/libgeos_c-fdac42b1.so.1.16.0', handle 3082f90 at 0x7f5af36a3eb8>, using it.
2022-03-02 14:50:42,248 [MainThread  ] [ERROR]  Uncaught exception
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    import web
  File "/home/dimat789/ultracam/web.py", line 31, in <module>
    app = Sanic()
  File "/home/dimat789/.local/lib/python3.6/site-packages/sanic/app.py", line 61, in __init__
    "Sanic instance cannot be unnamed. "
sanic.exceptions.SanicException: Sanic instance cannot be unnamed. Please use Sanic(name='your_application_name') instead.

**Comment by ghost** [comment]
Same thing happens here.
